### PR TITLE
BioImage.IO Core: Execute PlantSeg-compatible models by nickname

### PR DESCRIPTION
**Pull request by qin-yu**
## New: Predict with models from BioImage.IO Model Zoo

After Zenodo failed BioImage.IO and BioImage.IO's storage moved to EBI, this PR:

- is the first attempt for https://github.com/kreshuklab/plant-seg/issues/210
- makes prediction with models from BioImage.IO Model Zoo possible
  - limited to PlantSeg-compatible models, i.e. `UNet3D`s and `UNet2D`s trained with `pytorch-3dunet`
  - depend on `bioimageio.core` package now, but conda has no "extra"s like pip so it's made compulsory

The next step is to discuss with BioImage.IO team about filtering models and make PlantSeg community partner.

image

Prediction with PlantSeg Custom/Official models in PlantSeg Zoo is not affected:

image

### CODE REVIEW

**Comment by qin-yu** [comment]
I believe the introduction of BioImage.IO is significant enough for a new release, potentially v1.8.0. But I suggest we hold off on finalizing this until all related steps are completed.

**Comment by lorenzocerrone** [comment]
Hey Qin, looks great! And I am also up for a release. 

I have only two points to discuss before releasing: 
Screenshot from 2024-05-26 10-36-58
- When BioImage.IO is selected, should we hide the filters? Since the user needs to select the model name manually, I don't see why keeping them. 
- Is there a tag that can be used to select valid models in the bioimage zoom?

**Comment by qin-yu** [comment]
I'll do filters but because there is no one forcing users to upload a model with tags, filtering does't guarantee you to find the right models. However, there are ways to check compatibility, which can also be put to BioImage.IO for checking during upload. I'll do these two together as the next step. 

For removing the filters for BioImage.IO models we can actually keep them when the checks I mentioned above are done. I can remove them for a brief period. (I actually want to improve the filters because for modality and segmentation type there are more)****

**Comment by lorenzocerrone** [comment]
Perfect :) sounds good! Feel free to make a release when you are ready!

**Pull request merged**
