### PR TITLE
Add inference API and task for all BioImage.IO Model Zoo models

### PR DESCRIPTION
**Pull request by qin-yu**
## Add inference API and task for all BioImage.IO Model Zoo models

PlantSeg v2 supports training of our models and inference of all BioImage.IO models. This PR turns v2.0.0aX to v2.0.0b0.

### Main features

I integrated support for bioimageio.core inference with BioImage.IO Model Zoo models into the PlantSeg API, tasks, and widgets.

To ensure functionality, I conducted the following manual tests:
	1.	2D Input (YX): Tested with the `pioneering-rhino` PlantSeg model, resulting in a 2D image output.
	2.	3D Input (ZYX): Tested with the `emotional-cricket` PlantSeg model, resulting in a 3D image output.
	3.	4D Input (CZYX): Tested with the `philosophical-panda` Cellpose model, resulting in a sequence of 4D image outputs.

The bioimageio.core Python package has multiple versions, requiring careful handling of format compatibility and extensive validation. Ongoing development of the library introduces additional complexity, but I believe this implementation addresses most use cases and version-specific challenges.

### Screenshot

Multiple outputs of different sizes from Cellpose network:

CleanShot 2024-12-19 at 18 33 56@2x

List of BioImage.IO Model Zoo models:

CleanShot 2024-12-19 at 18 35 09@2x

### CODE REVIEW

**Comment by lorenzocerrone** [comment]
@qin-yu the ci seems to be stuck

**Comment by qin-yu** [comment]
> @qin-yu the ci seems to be stuck

PyTest finishes without error on macOS and Linux for me. Checking the CI now.

**Comment by qin-yu** [comment]
For the record, starting with Python 3.13, `pip` will no longer have `setuptools` and `wheel` as dependencies by default. So I put `setuptools` in the `meta.yaml`. [[*ref]](https://conda-forge.org/news/2024/08/21/sunsetting-pip-deps/ )

**Comment by qin-yu** [comment]
I rerun the CI for main branch and it got stuck as well:

- the original (pass): https://github.com/kreshuklab/plant-seg/actions/runs/12140679722
- the new run (stuck): https://github.com/kreshuklab/plant-seg/actions/runs/12382344338

**Comment by qin-yu** [comment]
Tried some solutions but none works:

CleanShot 2024-12-17 at 23 29 17@2x

**Pull request merged**
